export default [
  {
    id: 1,
    categorieId: 4,
    colorsId: [1, 2],
    name: 'Радионяня Motorola MBP16',
    price: 3690,
    image: 'img/radio.jpg',
  },
  {
    id: 2,
    categorieId: 1,
    colorsId: [4, 5, 6, 7],
    name: 'Ультразвуковая зубная щётка Playbrush Smart Sonic',
    price: 5660,
    image: 'img/toothbrush.jpg',
  },
  {
    id: 3,
    categorieId: 2,
    colorsId: [1, 2, 6],
    name: 'Смартфон Xiaomi Mi Mix 3 6/128GB',
    price: 21790,
    image: 'img/phone.jpg',
  },
  {
    id: 4,
    categorieId: 3,
    colorsId: [4, 5],
    name: 'Электроскейт Razor Cruiser',
    price: 24690,
    image: 'img/board.jpg',
  },
  {
    id: 5,
    categorieId: 2,
    colorsId: [2, 3, 5],
    name: 'Смартфон Xiaomi Mi A3 4/64GB Android One',
    price: 14960,
    image: 'img/phone-2.jpg',
  },
  {
    id: 6,
    categorieId: 2,
    colorsId: [6],
    name: 'Смартфон Xiaomi Redmi 6/128GB',
    price: 8960,
    image: 'img/phone-3.jpg',
  },
  {
    id: 7,
    categorieId: 3,
    colorsId: [6, 7],
    name: 'Электрический дрифт-карт Razor Crazy Cart',
    price: 39900,
    image: 'img/bicycle.jpg',
  },
  {
    id: 8,
    categorieId: 3,
    colorsId: [1, 2, 4, 5, 6],
    name: 'Гироскутер Razor Hovertrax 2.0',
    price: 34900,
    image: 'img/wheels.jpg',
  },
  {
    id: 9,
    categorieId: 3,
    colorsId: [4, 5, 7],
    name: 'Детский трюковой самокат Razor Grom',
    price: 4990,
    image: 'img/scooter.jpg',
  },
  {
    id: 10,
    categorieId: 3,
    colorsId: [2, 4, 6],
    name: 'Роллерсёрф Razor RipStik Air Pro',
    price: 6690,
    image: 'img/ripstik.jpg',
  },
  {
    id: 11,
    categorieId: 5,
    colorsId: [3, 5, 7],
    name: 'Наушники AirPods с беспроводным зарядным футляром',
    price: 16560,
    image: 'img/airpods.jpg',
  },
  {
    id: 12,
    categorieId: 5,
    colorsId: [1, 2, 4, 5, 7],
    name: 'Наушники Sony',
    price: 30690,
    image: 'img/headphones.jpg',
  },
];
